name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '4.7.x', '4.8.x', '3.1.x', '5.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} build
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build
      run: dotnet build --configuration Release
