name: Create release branch

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2      
    - name: Save release version
      uses: olegtarasov/get-tag@v2
      with: 
        tagRegex: "v*.*.*" 
    - name: Print release version
      run: echo "$GIT_TAG_NAME"
    
